/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    { type: 'category', label: 'Guide', collapsible: false, items: [
      { type: 'doc', id: 'introduction' },
      { type: 'doc', id: 'getting-started' },
      { type: 'doc', id: 'keymaps' },
      { type: 'doc', id: 'autocommands' },
      { type: 'doc', id: 'commands' },
    ]},
    { type: 'category', label: 'Modules', items: [
      {type: 'doc', id: 'modules/all-modules' },
      {type: 'doc', id: 'modules/building-custom-module'},
      {type: 'doc', id: 'modules/module-spec'},
      {type: 'category', label: 'Feature Modules', items: [
        {type: 'autogenerated', dirName: 'modules/features'}
      ]},
      {type: 'category', label: 'Language Modules', items: [
        {type: 'autogenerated', dirName: 'modules/langs'}
      ]},
      {type: 'category', label: 'Core Modules', items: [
        {type: 'autogenerated', dirName: 'modules/core'}
      ]},
    ]}
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
